name: Build and publish to PyPI

on: push
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'pyproject.toml'

jobs:
  # see cibuildwheel github for more
  # matrix built for building on all environments
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true           # TODO: for now, while debugging
      matrix:
        # no support for windows arm, because pypi rdkit does not support windows arm
        # latest supported rdkit version for macos intel is 2025.9.3
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-15-intel, macos-latest, windows-latest]

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Build wheels
      uses: pypa/cibuildwheel@v4.2.1
      with:
        package-dir: .
        output-dir: wheels

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: ./wheels/*.whl

  check_wheel_validity:
    name: Test ${{ matrix.os }} wheel validity in isolated environment
    runs-on: ${{ matrix.os }}
    needs: [build_wheels]
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-15-intel, macos-latest, windows-latest]
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: ci

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        cache: "pip"

    - uses: actions/download-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: wheels

    - name: Install and verify
      run: python ci/verify_install.py wheels
        
  upload_pypi:
    name: Publish package distributions to PyPI
    if: false
    needs: [build_wheels, check_wheel_validity]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
       id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist 
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
